language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

before_script: composer install

script:
  - mkdir -p coverage
  - php bin/phpunit

after_script:
  - chmod -R 777 coverage
  - ls -lhart coverage
  - if [ -f bin/coveralls ] ; then php bin/coveralls -v || true ; fi

notifications:
  email:
    on_success: change
    on_failure: change
