language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

cache:
  directories:
    - vendor
    - bin

before_script: composer install

script:
  - php bin/phpunit

after_success:
  - export CI_BUILD_NUMBER="$TRAVIS_BUILD_NUMBER"
  - export CI_PULL_REQUEST="$TRAVIS_PULL_REQUEST"
  - export CI_BRANCH="$TRAVIS_BRANCH"
  - travis_retry php bin/coveralls -vvv

notifications:
  email:
    on_success: change
    on_failure: change
