language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

before_script: composer install

script:
  - php bin/phpunit

after_success:
  - travis_retry php bin/coveralls -vvv

notifications:
  email:
    on_success: change
    on_failure: change
