language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

before_script: composer install

after_script:
  - if [ -f bin/coveralls ] ; then php bin/coveralls -v || true ; fi

notifications:
  email:
    on_success: change
    on_failure: change
