language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

cache:
  directories:
    - vendor
    - bin

before_script: composer install

script:
  - php bin/phpunit

after_success:
  - composer require codeclimate/php-test-reporter dev-master
  - bin/test-reporter

notifications:
  email:
    on_success: change
    on_failure: change

addons:
  code_climate:
    repo_token: f7ad1bc4bdf2238e43fa34a5e3b4ffe3696c60ead1690e6ef8c821526c12410a
